Repository WeekFood/WeekFood, pull requests merged in 2019-01, with the labels that each got.

#77 Actualizacion de TS de t_pruebas
  src/app/views/cliente/ts/landing.ts
  src/app/views/cliente/ts/main.ts
  src/app/views/cliente/ts/vistas_Principales.ts
Labels: feature

#76 Actualizacion SCSS de t_pruebas
  src/app/views/cliente/scss/abstracts/_colores.scss
  src/app/views/cliente/scss/components/_cabecera.scss
  src/app/views/cliente/scss/components/_carrusel.scss
  src/app/views/cliente/scss/components/_principal.scss
  src/app/views/cliente/scss/layout/_distribucion.scss
Labels: feature

#79 feat(#65) : Prevencion de repeticion de header(xxx) moviendolo a controller.
  src/app/controllers/ApiController.php
  src/app/controllers/CarruselController.php
  src/app/controllers/MenuController.php
  src/app/controllers/ProductosController.php
  src/core/MVC/Controller.php
Labels: feature

#83 feat(#67): Eliminar dependencia de TypeScript y portar scripts TS a JS
  build/build.sh
  package-lock.json
  package.json
  src/app/views/cliente/js/carrusel.js
  src/app/views/cliente/js/main.js
  src/app/views/cliente/js/vistas_Principales.js
  src/app/views/index.php
  tsconfig.json
Labels: feature

#85 feat(#84) : Copia de todas las vistas en un unico script.
  build/build.sh
  src/app/views/cliente/js/componentes/carrusel.js
  src/app/views/cliente/js/vistas/principales.js
  src/app/views/cliente/js/vistas/productos.js
  src/app/views/index.php
Labels: feature

#88 feat(#81) : Minificación automatizada de JS y CSS en post-construcción.
  build/build.sh
  build/minimizarJS.js
  package-lock.json
  package.json
  src/app/views/index.php
Labels: feature

#91 fix(#60): Carrusel cambiado a slick
  src/app/views/cliente/js/componentes/carrusel.js
  src/app/views/cliente/js/vistas/principales.js
  src/app/views/cliente/libs/slick-1.8.1/ajax-loader.gif
  src/app/views/cliente/libs/slick-1.8.1/fonts/slick.eot
  src/app/views/cliente/libs/slick-1.8.1/fonts/slick.svg
  src/app/views/cliente/libs/slick-1.8.1/fonts/slick.ttf
  src/app/views/cliente/libs/slick-1.8.1/fonts/slick.woff
  src/app/views/cliente/libs/slick-1.8.1/slick-theme.css
  src/app/views/cliente/libs/slick-1.8.1/slick.css
  src/app/views/cliente/libs/slick-1.8.1/slick.min.js
  src/app/views/cliente/scss/components/_carrusel.scss
  src/app/views/index.php
Labels: fix

#92 feat(#90) : Animacion despliegue menu movil.
  src/app/views/cliente/js/main.js
  src/app/views/cliente/scss/components/_cabecera.scss
  src/app/views/cliente/scss/components/_menu.scss
  src/app/views/index.php
Labels: feature

#100 feat(#99) : Separacion de main.js en varios archivos para facilitar el desarrollo.
  src/app/views/cliente/js/abstractos.js
  src/app/views/cliente/js/funciones.js
  src/app/views/cliente/js/init.js
Labels: feature

#103 rm(#101) : Feat de la pantalla de carga eliminado.
  src/app/views/cliente/js/funciones.js
Labels: eliminado

#107 feat(#106) : Redirect de php se notifica en js para ejecutarse desde cliente. PR(#106)
  src/cliente/js/funciones.js
  src/cliente/js/init.js
  src/cliente/js/vistas/principales.js
  src/core/MVC/ControllerException.php
  src/index.php
Labels: feature, fix

#120 feat(#114) : Componente modal.
  src/cliente/js/componentes/ventanaModal.js
  src/cliente/scss/components/_ventana-modal.scss
  src/cliente/scss/estilo.scss
Labels: feature

#123 feat(#119): [SCSS] Crear componente boton
  src/cliente/scss/abstracts/_colores.scss
  src/cliente/scss/components/_boton.scss
  src/cliente/scss/estilo.scss
Labels: feature

#124 fix(#122) : Rename de botones, prevencion de cerrar la ventana al clickar en contenido.
  src/cliente/js/componentes/ventanaModal.js
Labels: fix

#126 feat(#SN) : Sistema de notificaciones.
  src/cliente/js/componentes/notificacion.js
  src/cliente/scss/components/_notificacion.scss
  src/cliente/scss/estilo.scss
Labels: feature

#128 feat(#127) : Gestion de JSONs en cache.
  package-lock.json
  src/cliente/js/abstractos.js
  src/cliente/js/componentes/carrusel.js
  src/cliente/js/funciones.js
  src/cliente/js/vistas/productos.js
Labels: feature

#129 feat(#SN) : Base de datos de la rama t_prueba_menu-anidado.
  db/WeekFood.sql
Labels: feature

#138 feat(#118): Clases Carrito, Articulo y Producto
  build/minificarJS.sh
  src/cliente/js/core/carrito/Articulo.js
  src/cliente/js/core/carrito/Carrito.js
  src/cliente/js/modelos/Producto.js
Labels: feature

#140 feat(#132) Modificar BD
  db/WeekFood.sql
Labels: feature

#144 fix(#130): Margen de click de botones de cabecera
  src/cliente/index.html
  src/cliente/scss/components/_cabecera.scss
Labels: fix

#145 fix(#143) Arreglado ancho producto
  package-lock.json
  src/cliente/scss/components/_productos.scss
Labels: fix

#133 feat(#SN) : Menu anidado, y todo lo que conlleva.
  src/app/resources/MenuResource.php
  src/app/resources/ProductosResource.php
  src/cliente/js/abstractos.js
  src/cliente/js/funciones.js
  src/cliente/js/vistas/productos.js
  src/cliente/scss/components/_menu-expandido.scss
  src/cliente/scss/components/_menu.scss
  src/cliente/scss/estilo.scss
  src/cliente/scss/layout/_distribucion.scss
  src/configs/routes.php
Labels: feature

#135 feat(#131) : Gestor de productos para evitar llamadas a la API y mejorar el rendimiento.
  src/cliente/js/componentes/visualizacion.js
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/cliente/js/init.js
  src/cliente/js/modelos/Categoria.js
  src/cliente/js/modelos/Producto.js
Labels: feature

#139 feat(#115) : Interfaz Carrito, completamente funcional.
  src/cliente/index.html
  src/cliente/js/componentes/carrito.js
  src/cliente/js/init.js
  src/cliente/scss/components/_carrito.scss
  src/cliente/scss/estilo.scss
Labels: feature

#163 fix(#155) : Menu expandido pierde el borde redondeado en movil.
  src/cliente/scss/components/_menu-expandido.scss
Labels: fix

#162 fix(#160) : Añadida variable global para evitar el cierre abrupto de notificaciones.
  src/cliente/js/abstractos.js
  src/cliente/js/componentes/notificacion.js
Labels: fix

#161 feat(#148) : Trigger notificaciones la añadir o eliminar articulos del carrito.
  src/cliente/js/componentes/carrito.js
Labels: feature

#156 feat(#151) : Componente final.
  src/cliente/js/vistas/principales.js
  src/cliente/js/vistas/productos.js
  src/cliente/scss/components/_final.scss
  src/cliente/scss/estilo.scss
Labels: feature

#153 fix(#150) Arreglar titulo
  src/cliente/js/vistas/productos.js
  src/cliente/scss/components/_producto.scss
  src/cliente/scss/components/_productos.scss
Labels: fix

#166 fix(#158) : Reemplazado event.currentTarget por this, para facilitar la comprension del codigo.
  src/cliente/js/componentes/carrito.js
  src/cliente/js/vistas/productos.js
Labels: fix

#165 fix(#152): [Carrito] incrementar cantidad a traves del método propio
  src/cliente/js/core/carrito/Carrito.js
Labels: fix

#157 fix(#134) : Cache JSONS movido a Core.
  src/cliente/js/abstractos.js
  src/cliente/js/core/Cache_Jsons/CacheJSONs.js
  src/cliente/js/core/Cache_Jsons/JSONCacheado.js
  src/cliente/js/init.js
Labels: fix

#171 Update _ventana-modal.scss
  src/cliente/scss/components/_ventana-modal.scss
Labels: fix

#174 fix(#149) : Parseado id y precio, cambios de jsdoc.
  src/cliente/js/componentes/carrito.js
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/cliente/js/modelos/Producto.js
Labels: fix

#173 fix(#154) : BEM c-principal
  src/cliente/js/vistas/principales.js
  src/cliente/scss/components/_principal.scss
Labels: fix

#168 feat(#147) : Cambio de estilo segun el estado del carrito y los productos.
  src/cliente/js/componentes/carrito.js
  src/cliente/js/vistas/productos.js
  src/cliente/scss/components/_carrito.scss
  src/cliente/scss/components/_producto.scss
Labels: feature

#182 fix(#176) : Solucionado, se reescribia el html y por eso no se veian las clases
  src/cliente/js/componentes/carrito.js
Labels: fix

#187 fix(#186): Quitado código sobrante en carrito.js post PR #148
  src/cliente/js/componentes/carrito.js
Labels: fix

#185 fix(#183) : Campana reemplazada y boton pagar perfeccionado, legibilidad del codigo mejorada.
  src/cliente/js/componentes/carrito.js
  src/cliente/scss/components/_cabecera.scss
  src/cliente/scss/components/_carrito.scss
Labels: fix

#190 fix[#178] Cambio de letra mayuscula
  db/WeekFood.sql
Labels: fix

#194 fix(#177): [JS] Agregar producto por ventana modal no actualiza el botón en el grid
  src/cliente/js/componentes/carrito.js
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/cliente/js/vistas/productos.js
Labels: fix

#191 feat(#180): Estilizar menu-expandido
  src/cliente/js/vistas/productos.js
  src/cliente/scss/components/_menu-expandido.scss
Labels: feature

#195 feat(#193)(MYSQL) : Añadido descripción productos
  db/WeekFood.sql
Labels: feature

#192 fix(#179) : Puesto el titulo y la equis por encima del contenido, y el contenido no tapa los botones.
  src/cliente/scss/components/_ventana-modal.scss
Labels: fix

#202 fix(#201)(JS) : Carrito Global
  src/cliente/js/componentes/carrito.js
  src/cliente/js/init.js
  src/cliente/js/vistas/productos.js
Labels: fix

#208 fix(#207) : El carrito ya no se pliega cuando no debe.
  src/cliente/js/componentes/carrito.js
Labels: fix

#205 feat(#204) : Cambiado strings de notificaciones
  src/cliente/js/componentes/carrito.js
Labels: feature

#203 feat(#189) : Cambiar rutas de productos a query.
  src/app/resources/ProductosResource.php
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/configs/routes.php
  src/core/MVC/Router.php
Labels: feature

#206 feat(#197) : Ofertas funcionales.
  db/WeekFood.sql
  src/app/resources/ProductosResource.php
  src/cliente/js/abstractos.js
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/cliente/js/funciones.js
  src/cliente/js/vistas/principales.js
  src/cliente/js/vistas/productos.js
  src/configs/routes.php
Labels: feature

#210 fix(#209): [Modal Producto] Revisar tamaño y layout post #192
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/cliente/scss/components/_modal-producto.scss
Labels: fix

#212 fix(#211) : Cambios en la api para evitar respuestas erroneas, comprobacion sobrante eliminada
  src/app/resources/ProductosResource.php
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/core/MVC/Resource.php
Labels: fix

#216 Script despliegue Producción
  build/despl-preprod.sh
  build/despl-prod.sh
  package.json
  src/configs/prod_config.php
Labels: feature

#218 feat(#217) : Reducción de llamadas a la API.
  src/app/resources/ProductosResource.php
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/configs/routes.php
Labels: feature

#219 feat(#188) : Poner el articulo actualizado al final del carrito.
  src/cliente/js/core/carrito/Carrito.js
Labels: feature

#220 feat(#215) : Animación del menú en móvil mejorada.
  src/cliente/js/init.js
  src/cliente/scss/components/_menu.scss
Labels: feature

#222 feat(#199) : Guardar el carrito en BD
  db/WeekFood.sql
  src/app/resources/CarritosResource.php
  src/app/resources/ProductosResource.php
  src/cliente/js/abstractos.js
  src/cliente/js/componentes/carrito.js
  src/cliente/js/core/Gestion Productos/GestorProductos.js
  src/cliente/js/core/Usuario/Usuario.js
  src/cliente/js/core/carrito/Carrito.js
  src/cliente/js/init.js
  src/configs/routes.php
  src/core/MVC/Resource.php
  src/core/MVC/Router.php
Labels: feature

#229 feat(#181): [Grid Productos] Permitir abrir modal clickando en cualquier parte
  src/cliente/js/vistas/productos.js
  src/cliente/scss/components/_producto.scss
Labels: feature

#232 fix(#213): [Menu expandido] Arreglos checkbox
  src/cliente/scss/components/_menu-expandido.scss
Labels: fix

#231 feat(#224) : Añadido boton info opcional al tipo info, añadido jsdoc
  src/cliente/js/componentes/ventanaModal.js
Labels: feature

#235 feat(#233): [c-principal] Mejora visual del párrafo
  src/cliente/js/vistas/principales.js
  src/cliente/scss/components/_principal.scss
Labels: feature

#237 feat(#236): [c-carrito] Mejoras visuales
  src/cliente/js/componentes/carrito.js
  src/cliente/scss/components/_carrito.scss
Labels: feature

#226 feat(#82): [PHP] Sistema de autenticación (login) y registro
  src/app/resources/AuthResource.php
  src/configs/routes.php
  src/core/Auth/Auth.php
  src/core/Auth/NickTakenException.php
  src/core/Auth/UserNotFoundException.php
  src/core/Auth/WrongPasswordException.php
  src/index.php
Labels: feature
